Fix: Failed to build for nfs docker_image
Missing "ports" section before poer number

ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 13, column 7
expected <block end>, but found '-'
  in "./docker-compose.yml", line 15, column 7